# Generated by Django 5.0.6 on 2024-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
